### ISSUE TITLE
Could not connect to DB, check the creds in db-creds.inc: Server sent charset unknown to the client

### ISSUE THREAD

**Issue by elfgzp** [realVEct0r/sqli-labs-for-docker#2]
数据库无法初始化

**Comment by elfgzp** [comment]
指定一下数据库容器版本就好了，太新会有编码问题

**Comment by realvect0r** [comment]
see: https://github.com/realVEct0r/sqli-labs-for-docker/commit/3dc11f5983fdfde73a081b3151dc1507d3ba7b92

已经修改。感谢您的建议
